apiVersion: apps/v1
kind: Deployment
metadata:
  name: qualification-course-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qualification-course-service
  template:
    metadata:
      labels:
        app: qualification-course-service
    spec:
      containers:
      - image: vladstone13/qualification_course_service
        name: qualification-course-service