apiVersion: v1
kind: Service
metadata:
  labels:
    app: qualification-course-service
  name: qualification-course-service
spec:
  ports:
  - name: 83-8083
    port: 83
    protocol: TCP
    targetPort: 8083
  selector:
    app: qualification-course-service
  type: ClusterIP
