apiVersion: v1
kind: Service
metadata:
  labels:
    app: training-service
  name: training-service
spec:
  ports:
  - name: 82-8082
    port: 82
    protocol: TCP
    targetPort: 8082
  selector:
    app: training-service

