apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-tms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-tms
  template:
    metadata:
      labels:
        app: db-tms
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: tms
            - name: POSTGRES_PASSWORD
              value: "13102001"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: IfNotPresent
          name: db-tms
          ports:
            - containerPort: 5432
