apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-market-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer-market-service
  template:
    metadata:
      labels:
        app: transfer-market-service
    spec:
      containers:
      - image: vladstone13/transfer_market_service
        name: transfer-market-service
        ports:
          - containerPort: 8081
            name: customers
