apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-world-service
  template:
    metadata:
      labels:
        app: football-world-service
    spec:
      containers:
      - image: vladstone13/football_world_service
        name: football-world-service
