apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: football-world-service
  template:
    metadata:
      labels:
        app: football-world-service
    spec:
      containers:
      - image: football-world-service:snapshot
        name: football-world-service
    env:
      - name: POSTGRES_ENDPOINT
        value: "jdbc:postgresql://172.17.0.2:5432/"
      - name: POSTGRES_PASSWORD
        value: "13102001"
      - name: POSTGRES_USERNAME
        value: "postgres"
