apiVersion: v1
kind: Service
metadata:
  labels:
    app: football-world-service
  name: football-world-service
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: football-world-service
  type: ClusterIP

